# Generated by Django 6.0.2 on 2026-02-11 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('matter_type', models.CharField(choices=[('transaction', 'Real Estate Transaction'), ('land_use', 'Land Use / Zoning')], max_length=20)),
                ('default_reminder_days', models.JSONField(default=list, help_text='List of days before deadline to send reminders, e.g. [30, 14, 7, 3, 1]')),
            ],
            options={
                'ordering': ['matter_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('matter_type', models.CharField(choices=[('transaction', 'Real Estate Transaction'), ('land_use', 'Land Use / Zoning')], max_length=20)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('closed', 'Closed')], default='active', max_length=10)),
                ('asana_project_id', models.CharField(blank=True, help_text='Asana project GID for syncing', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='deadlines.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Additional details about this specific deadline')),
                ('reminder_days', models.JSONField(blank=True, default=list, help_text='Override reminder days for this deadline. Leave empty to use deadline type defaults.')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('extended', 'Extended'), ('waived', 'Waived')], default='upcoming', max_length=10)),
                ('asana_task_id', models.CharField(blank=True, help_text='Asana task GID if synced', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='deadlines.deadlinetype')),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='deadlines.matter')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('days_before', models.IntegerField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='deadlines.deadline')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
