# Generated by Django 6.0.2 on 2026-03-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='notify',
            field=models.BooleanField(default=False, help_text='Send email reminders to matter contacts for this deadline'),
        ),
        migrations.CreateModel(
            name='MatterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, help_text='e.g. Client, Buyer, Seller, Broker, Lender', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='deadlines.matter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
