# Generated by Django 6.0.2 on 2026-03-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_deadline_notify_mattercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='day_type',
            field=models.CharField(blank=True, choices=[('calendar', 'Calendar Days'), ('business', 'Business Days')], default='calendar', max_length=10),
        ),
        migrations.AddField(
            model_name='deadline',
            name='is_calculated',
            field=models.BooleanField(default=False, help_text='Whether this date is calculated from a reference deadline'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='offset_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days offset from reference deadline', null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='reference_deadline',
            field=models.ForeignKey(blank=True, help_text='The deadline this date is calculated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='deadlines.deadline'),
        ),
        migrations.AddField(
            model_name='deadlinetype',
            name='default_day_type',
            field=models.CharField(choices=[('calendar', 'Calendar Days'), ('business', 'Business Days')], default='calendar', help_text='Default day type for offset calculation', max_length=10),
        ),
        migrations.AddField(
            model_name='deadlinetype',
            name='default_offset_days',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of days offset from reference deadline', null=True),
        ),
        migrations.AddField(
            model_name='deadlinetype',
            name='default_reference_type',
            field=models.ForeignKey(blank=True, help_text='Default reference deadline type for calculated dates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_types', to='deadlines.deadlinetype'),
        ),
    ]
